Various schedule update
paug/android-makers-2022 pull request #137
Opened 2022-04-12 15:26 UTC by loutry

- fix Yacine session duration
- Withdraw Chris and his session
- Add Nick Butcher as speaker
- Specify remotely given session by adding a note in their descriptions

2022-04-13 18:35 UTC, djavan-bertrand requested changes
images/logos/qonto-margin.png ne sert à rien j'ai l'impression

2022-04-13 18:35 UTC, djavan-bertrand commented on data/database/partners.json
> +                "order": 1,
```suggestion
                "order": 2,
```

2022-04-13 18:38 UTC, martinbonnin approved these changes

2022-04-14 11:18 UTC, benju69 commented
> images/logos/qonto-margin.png ne sert à rien j'ai l'impression

oui j'en ai fait 2, quand je corrigeais la marge, pas grave de laisser

2022-04-14 12:02 UTC, djavan-bertrand approved these changes

2022-04-14 15:46 UTC, merged